language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

cache: cargo

after_success: ./kcov.sh

stages:
  - test
  - deploy

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
#   include: # disable for now, while not having a gh-page
#     - name: 'Deploy to GitHub Pages'
#       stage: deploy
#       if: branch IN (master) AND NOT type IN (pull_request) # i know this redundant, but it is needed otherwise the test will always create a deploy of this
#       script: bash ./ghPagesPre.sh
#       deploy:
#         provider: pages
#         skip_cleanup: true
#         github_token: $GITHUB_GH_PAGES
#         keep_history: false
#         target_branch: gh-pages # i know this the default, but just to be sure
#         on:
#           branch:
#             - master
